import { Link, useLoaderData } from "react-router";
import type { Route } from "./+types/claim-detail";
import { loadOr404 } from "../lib/api.server";
import { pageMeta } from "../lib/seo";

type Evidence = { kind: "support" | "conflict" | "related"; url: string; quote: string; source: string };
type Claim = { id: number; claim: string; claimZh?: string | null; claimant: string; claimantName?: string | null; claimantType?: string | null; claimantInterest?: string | null; claimType: string; originalSource: string; evidence: Evidence[]; status: string; missingEvidence: string; topicKey: string | null; topicLabel: string | null; supportCount?: number; conflictCount?: number; relatedCount?: number };
export async function loader({ request, params }: Route.LoaderArgs) { return loadOr404<Claim>(`/api/site/claims/${encodeURIComponent(params.id ?? "")}`, { signal: request.signal }); }
export function meta({ loaderData }: Route.MetaArgs) { return pageMeta({ title: loaderData?.claimZh ?? "AI 牛皮账本", description: "公开 Claim 证据详情。", path: `/claims/${loaderData?.id ?? ""}` }); }
export default function ClaimDetailPage() { const c = useLoaderData<typeof loader>(); return <div className="pb-10"><header className="pb-5 pt-5 lg:pt-1"><Link to="/claims" className="text-[12px] text-accent">← AI 牛皮账本</Link><h1 className="mt-2 text-[25px] font-bold text-ink">{c.claimZh ?? c.claim}</h1><div className="mt-2 flex flex-wrap gap-2 text-[12px] text-ink-4"><span>{c.claimantName ?? c.claimant}</span><span>·</span><span>{c.claimType}</span><span className="rounded bg-bg-sunk px-2 py-0.5">{c.status}</span></div></header><div className="space-y-3"><section className="card p-5"><h2 className="text-[14px] font-bold text-ink">原始 Claim</h2><p className="mt-2 text-[13px] leading-relaxed text-ink-2">{c.claim}</p><a href={c.originalSource} target="_blank" rel="noreferrer" className="mt-3 inline-block break-all text-[12px] text-accent">打开原始出处 ↗</a></section><section className="card p-5"><h2 className="text-[14px] font-bold text-ink">证据</h2>{c.evidence.length ? <ul className="mt-3 space-y-3">{c.evidence.map((e,i) => <li key={`${e.url}-${i}`} className="text-[13px] leading-relaxed"><span className={`mr-2 rounded px-1.5 py-0.5 text-[11px] ${e.kind === "support" ? "bg-ok-soft text-ok-ink" : e.kind === "conflict" ? "bg-hot-soft text-hot" : "bg-bg-sunk text-ink-3"}`}>{e.kind === "support" ? "支持" : e.kind === "conflict" ? "冲突" : "相关材料"}</span><a href={e.url} target="_blank" rel="noreferrer" className="text-accent">{e.source}</a><p className="mt-1 text-ink-3">{e.quote}</p></li>)}</ul> : <p className="mt-2 text-[13px] text-ink-3">暂未找到可直接支持或冲突的独立证据。</p>}</section><section className="card p-5"><h2 className="text-[14px] font-bold text-ink">还缺什么证据</h2><p className="mt-2 text-[13px] leading-relaxed text-ink-3">{c.missingEvidence || "暂无"}</p></section></div></div>; }
