import { Link, useLoaderData } from "react-router";
import type { Route } from "./+types/demand-detail";
import { loadOr404 } from "../lib/api.server";
import { pageMeta } from "../lib/seo";

type Sample = { id: number; problem: string; problemZh?: string | null; scenario: string; scenarioZh?: string | null; workaround: string; workaroundZh?: string | null; evidence: string; originalUrl: string; sourceName: string; sourceUser: string | null; observedAt: string };
type Data = { themeKey: string; themeTitle: string; sampleCount: number; sourceCount: number; independentUserCount: number; independentThreadCount: number; independentRepoCount: number; independentPlatformCount: number; demandState: "multi_user" | "single_signal"; latestAt: string; samples: Sample[] };
export async function loader({ request, params }: Route.LoaderArgs) { return loadOr404<Data>(`/api/site/demands/${encodeURIComponent(params.themeKey ?? "")}`, { signal: request.signal }); }
export function meta({ loaderData }: Route.MetaArgs) { return pageMeta({ title: loaderData?.themeTitle ?? "真需求", description: "真实用户需求详情。", path: `/demands/${loaderData?.themeKey ?? ""}` }); }
function stamp(v: string) { return new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(v)); }
export default function DemandDetailPage() { const d = useLoaderData<typeof loader>(); const first = d.samples[0]; const scenario = first?.scenarioZh ?? first?.scenario ?? ""; return <div className="pb-10"><header className="pb-5 pt-5 lg:pt-1"><Link to="/demands" className="text-[12px] text-accent">← 真需求</Link><h1 className="mt-2 text-[25px] font-bold text-ink">{d.themeTitle}</h1><p className="mt-2 text-[13px] text-ink-3">{d.independentUserCount} 个独立用户 · {d.independentThreadCount} 个独立线程 · {d.independentRepoCount} 个仓库 · {d.independentPlatformCount} 个平台 · {d.sampleCount} 条原始样本 · 最近活跃 {stamp(d.latestAt)}</p></header><section className="space-y-3"><article className="card p-5"><h2 className="text-[15px] font-bold text-ink">问题</h2><p className="mt-2 text-[15px] leading-relaxed text-ink">{d.themeTitle}</p><p className="mt-4 text-[13px] leading-relaxed text-ink-3"><b className="text-ink-4">使用场景：</b>{/问题是什么|日常编码或自动化任务|未说明具体复现/.test(scenario) ? "原文未明确说明具体使用场景" : scenario}</p><p className="mt-2 text-[13px] leading-relaxed text-ink-3"><b className="text-ink-4">临时解决办法：</b>{first?.workaroundZh ?? first?.workaround ?? "暂未发现明确临时解决办法。"}</p></article><h2 className="pt-3 text-[17px] font-bold text-ink">真实反馈</h2>{d.samples.map((s) => <article key={s.id} className="card px-5 py-4"><div className="flex flex-wrap gap-2 text-[11.5px] text-ink-4"><span>{s.sourceName}</span><span>{s.sourceUser ? `@${s.sourceUser}` : "匿名用户"}</span><time dateTime={s.observedAt}>{stamp(s.observedAt)}</time></div><p className="mt-2 text-[13.5px] leading-relaxed text-ink-2">{s.problemZh ?? s.problem}</p><p className="mt-2 border-l-2 border-accent/40 pl-3 text-[12.5px] leading-relaxed text-ink-3">“{s.evidence}”</p><a href={s.originalUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block text-[12px] text-accent">查看原文 ↗</a></article>)}</section></div>; }
