import { Link, useLoaderData } from "react-router";
import type { Route } from "./+types/signal-topic";
import { loadOr404 } from "../lib/api.server";
import { pageMeta } from "../lib/seo";
import { displayClaimant, displaySource, publicText } from "../lib/public-text";

type Demand = { id: number; problem: string; problemZh?: string | null; scenario: string; scenarioZh?: string | null; workaround: string; workaroundZh?: string | null; evidence: string; originalUrl: string; sourceName: string; sourceUser: string | null };
type Claim = { id: number; claim: string; claimZh?: string | null; claimant: string; status: string; originalSource: string; evidence: Array<{ kind: string; url: string; quote: string; source: string }>; missingEvidence: string };
type Data = { topic: { key: string; label: string }; demands: Demand[]; claims: Claim[] };

export async function loader({ request, params }: Route.LoaderArgs) { return loadOr404<Data>(`/api/site/signals/topics/${encodeURIComponent(params.topicKey ?? "")}`, { signal: request.signal }); }
export function meta({ loaderData }: Route.MetaArgs) { return pageMeta({ title: publicText(loaderData?.topic.label, "主题详情"), description: "现实雷达主题详情：真实需求与公开主张。", path: `/signals/topic/${loaderData?.topic.key ?? ""}` }); }
export function headers() { return { "Cache-Control": "public, max-age=0, s-maxage=60, stale-while-revalidate=120" }; }

export default function SignalTopicPage() { const data = useLoaderData<typeof loader>(); return <div className="pb-10">
  <header className="pb-5 pt-5 lg:pt-1"><Link to="/signals" className="text-[12px] text-accent">← 人工智能现实雷达</Link><h1 className="mt-2 text-[25px] font-bold text-ink">{publicText(data.topic.label, "主题详情")}</h1><p className="mt-1 text-[13px] text-ink-3">共享主题</p></header>
  <section><h2 className="mb-3 text-[17px] font-bold text-ink">真实需求 <span className="mono ml-1 text-[12px] font-normal text-ink-4">{data.demands.length}</span></h2><div className="space-y-3">{data.demands.map((item) => <article key={item.id} className="card px-5 py-4"><div className="text-[11.5px] text-ink-4">{displaySource(item.sourceName)} · 来源用户：匿名</div><h3 className="mt-2 text-[15px] font-semibold text-ink">{publicText(item.problemZh, "暂未生成中文摘要，请查看原文")}</h3><p className="mt-1.5 text-[13px] leading-relaxed text-ink-3">场景：{publicText(item.scenarioZh, "暂未生成中文场景，请查看原文")}</p><p className="mt-1 text-[13px] leading-relaxed text-ink-3">临时解决办法：{publicText(item.workaroundZh, "暂未发现明确临时解决办法")}</p><p className="mt-2 border-l-2 border-accent/40 pl-3 text-[12.5px] text-ink-3">原文摘录暂不在页面展开。</p><a href={item.originalUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block text-[12px] text-accent">查看原文 ↗</a></article>)}</div></section>
  <section className="mt-7"><h2 className="mb-3 text-[17px] font-bold text-ink">牛皮账本 <span className="mono ml-1 text-[12px] font-normal text-ink-4">{data.claims.length}</span></h2><div className="space-y-3">{data.claims.map((item) => <article key={item.id} className="card px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-[11.5px] text-ink-4">{displayClaimant(item.claimant)}</span><span className="rounded bg-bg-sunk px-2 py-0.5 text-[11.5px] text-ink-3">{item.status}</span></div><h3 className="mt-2 text-[15px] font-semibold text-ink">{publicText(item.claimZh, "暂无中文主张")}</h3><a href={item.originalSource} target="_blank" rel="noreferrer" className="mt-2 inline-block text-[12px] text-accent">查看原始来源 ↗</a>{item.evidence.length > 0 && <ul className="mt-3 space-y-1.5 border-t border-line-soft pt-3 text-[12.5px] text-ink-3">{item.evidence.map((e, i) => <li key={`${e.url}-${i}`}><span className="mr-1.5 rounded bg-bg-sunk px-1.5 py-0.5 text-[11px]">{e.kind === "support" ? "支持" : e.kind === "conflict" ? "冲突" : "相关材料"}</span><a href={e.url} target="_blank" rel="noreferrer" className="text-accent">查看来源</a> — 原文摘录暂不在页面展开。</li>)}</ul>}<p className="mt-2 text-[12px] text-ink-4">缺失证据：{item.missingEvidence || "暂无"}</p></article>)}</div></section>
 </div>; }
